### ISSUE TITLE
我搭建的节点，等了挺长时间都连不上peers

### ISSUE THREAD

**Issue by COLUD4** [DeepBrainChain/DBC-DOC#1]
![截屏2021-11-25 下午5 37 08](https://user-images.githubusercontent.com/21240219/143416792-bbca1695-d01b-45a5-8bc6-a73b3b2ad4c5.png)

**Comment by kevinye-2017** [comment]
这叼毛级别的团队写出的文档

**Comment by kaigedong** [comment]
有时候种子节点连接过多时会拒绝新连接，一般等一段时间能连上。最近升级了，允许更多的节点连接，网络通畅时一般不会出现这种情况了。
